### ISSUE TITLE
Restrict the hook to a specific branch?

### ISSUE THREAD

**Issue by Kraymer** [ecugol/pre-commit-hooks-django#1]
Hello @ecugol 

Where I work, we authorize not commiting (automatic) migrations in feature branch to avoid having unnecessary conflicts when merging back into hotfix/dev branch.

Could you add an argument `branches` to your plugin so I can enable it for the `master` branch only ?

**Comment by ecugol** [comment]
Hello @Kraymer, take a look at the latest release, it now supports specifying branches to work on.

**Comment by Kraymer** [comment]
Thanks, I'll give it a try next week then
